services:
  efoodweb:
    image: ${DOCKER_REGISTRY-}efoodweb
    build:
      context: .
      dockerfile: EFoodWeb/EFoodWeb/Dockerfile
    ports:
      - "5795:8080"
    environment:
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    restart: unless-stopped